### ISSUE TITLE
cannot light candles

### ISSUE THREAD

**Issue by Avaviks** [Lomie02/Musophobia#10]
Picking up the lighter and pressing 'E' to use it on the candle does not light the candle. This feature may not be implemented yet but if it is meant to be implemented then it isn't working.

**Comment by Lomie02** [comment]
Feature seems to be working fine? Did you turn the lighter on?

**Comment by Avaviks** [comment]
I did not turn the lighter on as the tutorial text does not appear until after reading a note. The feature does work as intended.
