### ISSUE TITLE
Pause menu does not cover whole screen

### ISSUE THREAD

**Issue by Avaviks** [Lomie02/Musophobia#28]
Musophobia Gold Build Version 0.6

The red background of the pause menu doesn't cover the top of the screen. Some parts of the HUD is also in front of the pause menu. It is unclear whether that is intentional.
![image](https://user-images.githubusercontent.com/90746873/201582775-a7b2a9de-4a36-47c2-8f6c-00701850414c.png)

**Comment by liamcoolrees** [comment]
will fix now

**Comment by liamcoolrees** [comment]
should be fixed, will submit v0.7 tomorrow, please test
![pausemenu](https://user-images.githubusercontent.com/81119667/201585094-4caa5a21-b1f9-4f43-b68e-655561ff4446.PNG)
