### ISSUE TITLE
the key becomes deformed when it moves

### ISSUE THREAD

**Issue by Avaviks** [Lomie02/Musophobia#3]
I don't know how but I bumped the key off the side table and it ended looking like this. This is likely a scaling issue either with the key or with an object the key is a child of.
![image_2022-09-28_104538931](https://user-images.githubusercontent.com/90746873/192662429-8ac0adb3-9bfb-4653-802b-bb4fe5f246e3.png)

**Comment by Lomie02** [comment]
Knocking keys off has been fixed & keys becoming deformed has been fixed
