### ISSUE TITLE
The car cannot be picked up by hovering over.

### ISSUE THREAD

**Issue by Avaviks** [Lomie02/Musophobia#31]
Musophobia Gold Build Version 0.6

The hand UI needs to be aimed to the right of the car to be able to pick it up. Aiming directly at the car does not display the hand UI. Pressing the pick up button only works when aiming to the right of the car.
![image](https://user-images.githubusercontent.com/90746873/201584266-fafd1247-4d8a-46fe-901a-6ecffb927aad.png)

**Comment by Avaviks** [comment]
The police report and the key next to it appear to have the same issue.

**Comment by liamcoolrees** [comment]
I am not encountering that error on my end so it should be fixed but i'll double check tomorrow

**Comment by Avaviks** [comment]
The drawer has the same issue.

**Comment by liamcoolrees** [comment]
Fixed Possibly?
