### ISSUE TITLE
the light from the torch does not match the player view

### ISSUE THREAD

**Issue by Avaviks** [Lomie02/Musophobia#4]
![image_2022-09-28_105055809](https://user-images.githubusercontent.com/90746873/192662906-a0ac0252-1ad0-4cdb-ada2-f61226abe247.png)

**Comment by Avaviks** [comment]
It looks the light is coming from somewhere to the right of the camera. My suggestion would be to make the light come from the camera so that the light doesn't mess up no matter how close the player gets to an object.

**Comment by Lomie02** [comment]
Light has been centered so it aligns with the players view
