### ISSUE TITLE
Inventory UI doesn't update when items are removed

### ISSUE THREAD

**Issue by Avaviks** [Lomie02/Musophobia#41]
Musophobia Gold Build Version 0.6

When a key is used and is thus removed from the player's hand and inventory, it still displays as being in the player's inventory on the HUD. This also happens when items are dropped. This only happens if the item that is removed is from a slot of a lower number than at least one other item in the inventory.

The issue can be fixed by changing selected inventory slot.

**Comment by Avaviks** [comment]
Musophobia V0.7 Beta Build (15.11 @ 2pm)

Appears to be fixed in this version.

**Comment by Avaviks** [comment]
Musophobia V0.7 Beta Build (15.11 @ 2pm)

This bug no longer occurs when an item is dropped but it does occur when a key is used on a door. The key must be in any slot to the left of another item in the inventory to occur.

**Comment by Avaviks** [comment]
Musophobia V0.7 Beta Build (15.11 @ 2pm)

This bug might be 2 separate bugs. Dropping items does not update the inventory UI if there are any items to the left of the dropped item.

**Comment by Lomie02** [comment]
I think this issue has been fixed, if not re-open this issue

**Comment by Lomie02** [comment]
I have tested this in the new scene & I can confirm the UI does update correctly with objects

**Comment by Lomie02** [comment]
This should be fixed now, hopefully. Try it on main & let me know

**Comment by Avaviks** [comment]
It is fixed for dropping items but not for using keys. Now if there any items in any other slot in your inventory when you use a key, the key doesn't disappear from the inventory UI.

**Comment by Lomie02** [comment]
I tested that but it doesn't happen to me, is it all keys or only some? How many items are you holding?

**Comment by Lomie02** [comment]
Oh never mind I accidentally fixed it, that's why I couldn't replicate it. I will get it on main
