### ISSUE TITLE
Pause UI can cover screen after closing a note

### ISSUE THREAD

**Issue by Avaviks** [Lomie02/Musophobia#44]
If the player pauses the game while the player is viewing a note, the pause UI does not display and the game is not paused. That is the expected result. However, once the player closes the note the pause menu UI covers the screen but does not pause the game. Pressing the pause button again closes the pause menu UI fixing the issue.

**Comment by Lomie02** [comment]
Player can no longer pause while reading notes. Issue has been resolved

**Comment by Lomie02** [comment]
Git didn't keep the change I did but I have fixed it again, let me know how it goes

**Comment by Lomie02** [comment]
I am going to assume this is fixed now but if it is not fixed please re-open this issue
