### ISSUE TITLE
the lighter disappears when picked up

### ISSUE THREAD

**Issue by Avaviks** [Lomie02/Musophobia#5]
When the lighter was picked up it immediately began falling out the player hand. It fell through the floor and was unretrievable.

To replicate this bug:
1. pick up the master bedroom key
2. use the master bedroom key on the master bedroom door
3. pick up the lighter

Dropping the master bedroom key instead of using it does not cause this issue.

**Comment by Avaviks** [comment]
In the case that the player has both the lighter and the master bedroom key in their inventory. When they use the key and swap back to the lighter, the lighter will still be held correctly. If the player however attempts to drop the lighter, it will not be dropped and instead no longer be lit by the player's close-up light (It can still be lit by the torch and hallway light).

**Comment by Lomie02** [comment]
Resolved bug with keys causing objects & lighter to fall through the floor
