### ISSUE TITLE
you can use object collision to pass into into and through objects and walls

### ISSUE THREAD

**Issue by Avaviks** [Lomie02/Musophobia#8]
When walking into the corner between 2 objects you can use the collision to push yourself through 1 of the colliders.

https://user-images.githubusercontent.com/90746873/192665798-ce5f56c6-775e-4e44-b82f-8945255bef22.mp4

**Comment by Avaviks** [comment]
This bug can be used to pass through walls. You need to be sprinting to make the bug occur.

**Comment by Lomie02** [comment]
Bug has been resolved, was an issue with the standing mirrors box collider

**Comment by Avaviks** [comment]
The bug can no longer be replicated on the standing mirror. However, this issue occurs in more places than just that standing mirror. To replicate you need to sprint at the spot in between 2 box colliders. 

This issue was found on the commit to main called "Merge branch 'liams-branch' into main" at 2:30PM 10/10/2022 in the scene "Level_House_Fixing 1". If each location needs to be fixed individually then I can create a list of every location where this bug is found.

https://user-images.githubusercontent.com/90746873/194799863-63ae5905-bd14-4ff7-a7c2-c1e7e2dd2a2f.mp4

**Comment by Lomie02** [comment]
This issue can be fixed by adjusting the colliders on the objects, avoid triangles & keep colliders flat against walls. A bunch of boxes should share a collider & not have their own.
