### ISSUE TITLE
rotating a held item also rotates the torch

### ISSUE THREAD

**Issue by Avaviks** [Lomie02/Musophobia#9]
If the player presses 'R' while holding a key or the lighter, they can drag their mouse around to rotate the torch and the held object. Pressing 'R' again stops the rotation. This also resets the torches rotation to the correct position but not the rotation of the held object. Pressing 'R' while not holding an object does nothing.
https://user-images.githubusercontent.com/90746873/192666312-16939132-eddd-4106-ba1d-deb3320c7dc9.mp4

**Comment by Lomie02** [comment]
Fixed
